# Generated by Django 3.2 on 2021-05-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzerias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Name',
        ),
    ]
